### ISSUE TITLE
Imports incorrectly sorted

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.CMFCore#101]
When running `tox -e lint` more than twenty occurrences of incorrectly sorted imports are listed.
But running this environment does not lead to a failure. It only lists these problems.

Is this the original idea: only listing them so that someone who sees them can fix them?

**Comment by dataflake** [comment]
Yes that is the intent. Running a tox or a linting process should never make changes itself, just point them out.

**Comment by icemac** [comment]
So we could fix the imports to get rid of this long list. Let's wait for #100 to be merged to reduce the number of conflicts.
