### ISSUE TITLE
New release: 2.5.4

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/Products.CMFCore#117]
Can we have a new release, so the incompatibility with the newer GenericSetup is fixed?
I am happy to do a release myself if you grant `maurits` (or `plone`) PyPI rights:
https://pypi.org/project/Products.CMFCore/

**Comment by dataflake** [comment]
2.5.4 is released now.

**Comment by mauritsvanrees** [comment]
Thanks!
