### ISSUE TITLE
Broken tests since Zope 5.5 release

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.CMFCore#120]
It seems that the changes in cookie handling in Zope 5.5 (https://github.com/zopefoundation/Zope/issues/1010) broke a test here.
```python
Error in test testCookieLogin (Products.CMFCore.tests.test_CookieCrumbler.CookieCrumblerTests)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/runner/work/Products.CMFCore/Products.CMFCore/src/Products/CMFCore/tests/test_CookieCrumbler.py", line 161, in testCookieLogin
    self.assertEqual(resp.cookies['__ac']['path'], '/')
KeyError: 'path'
```

Source: https://github.com/zopefoundation/Products.CMFCore/runs/5527462983?check_suite_focus=true#step:6:247

cc @d-maurer @dataflake

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2022-3-15 05:17 -0700:
>It seems that the changes in cookie handling in Zope 5.5 (https://github.com/zopefoundation/Zope/issues/1010) broke a test here.
>```python
>Error in test testCookieLogin (Products.CMFCore.tests.test_CookieCrumbler.CookieCrumblerTests)
>Traceback (most recent call last):
>  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
>    yield
>  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/unittest/case.py", line 592, in run
>    self._callTestMethod(testMethod)
>  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
>    method()
>  File "/home/runner/work/Products.CMFCore/Products.CMFCore/src/Products/CMFCore/tests/test_CookieCrumbler.py", line 161, in testCookieLogin
>    self.assertEqual(resp.cookies['__ac']['path'], '/')
>KeyError: 'path'
>```
>
>Source: https://github.com/zopefoundation/Products.CMFCore/runs/5527462983?check_suite_focus=true#step:6:247
>
>cc @d-maurer @dataflake

Cookie parameters now use internally the "official" names, i.e.
the "Path" parameter is now named "Path" (no longer "path").
>
>--
>Reply to this email directly or view it on GitHub:
>https://github.com/zopefoundation/Products.CMFCore/issues/120
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
--
Dieter
