### ISSUE TITLE
New release for Py 3.10 compatibility

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/Products.CMFCore#123]
Can we have a new release for Python 3.10 compatibility please?
Same for a few other packages:

- [X] Products.CMFUid https://pypi.org/project/Products.CMFUid/3.3/
- [x] Products.ExternalMethod https://pypi.org/project/Products.ExternalMethod/4.6/
- [x] Products.PluginRegistry https://pypi.org/project/Products.PluginRegistry/1.10/
- [x] Products.PythonScripts https://github.com/zopefoundation/Products.PythonScripts/pull/57 + https://pypi.org/project/Products.PythonScripts/4.14/
- [x] Products.Sessions https://pypi.org/project/Products.Sessions/4.13/
- [x] Products.CMFCore https://pypi.org/project/Products.CMFCore/2.6.0/

I have checked, and there are no recent (this year) open issues or PRs for these packages.
@icemac and @dataflake have PyPI rights on all. If you grant `maurits` rights, I am happy to release them.

No big hurry, but within a week would be nice.

**Comment by icemac** [comment]
I am starting now to create PRs to add Python 3.10 support for these packages.

**Comment by icemac** [comment]
> I am starting now to create PRs to add Python 3.10 support for these packages.

Interestingly I already did this months ago, so I checked the packages and created releases. Only Products.PythonScripts needed a PR.

**Comment by mauritsvanrees** [comment]
Thanks a lot!

**Comment by icemac** [comment]
Releases all requested packages, see the ticket description.
