### ISSUE TITLE
We don't have locales folder

### ISSUE THREAD

**Issue by wesleybl** [zopefoundation/Products.CMFCore#135]
## BUG/PROBLEM REPORT / FEATURE REQUEST

We don't have locales folder to add translations from `cmf_default` domain.

### What I did:

I accessed the repository code: https://github.com/zopefoundation/Products.CMFCore/tree/master/src/Products/CMFCore

### What I expect to happen:

Have a `locales` folder, to add translations.

### What actually happened:

We don't have the `locales` folder.

### What version of Python and Zope/Addons I am using:

Zope 5.9
Python 3.11

**Comment by davisagli** [comment]
There's one in CMFDefault: https://github.com/zopefoundation/Products.CMFDefault/blob/master/Products/CMFDefault/locales/cmf_default.pot

It does seem a bit odd to me that there are files in CMFCore which use the cmf_default domain. Should there be a cmf_core domain? Plone is based on CMFCore but not (any longer) CMFDefault.

@wesleybl Probably the most expedient way to add these translations for Plone would be to put them in https://github.com/collective/plone.app.locales

**Comment by wesleybl** [comment]
@davisagli following the `Products.CMFDefault` example, wouldn't it be better for the `Products.CMFCore` translations to stay in the product itself? I don't see a lot of "Zope Stuff" being translated into plone.app.locales. Anyway, maybe this is more of a convenience thing.

**Comment by davisagli** [comment]
@wesleybl I'd be in favor of adding them here, but I'd like to make sure the maintainers are okay with it...
