### ISSUE TITLE
Recursively deleting local roles leads to multiple reindexing of the same objects

### ISSUE THREAD

**Issue by petschki** [zopefoundation/Products.CMFCore#139]
We're investigating very long running times when deleting a user in a Plone site with many objects.

One of the issues we've found is, that the `deleteLocalRoles` here https://github.com/zopefoundation/Products.CMFCore/blob/master/src/Products/CMFCore/MembershipTool.py#L457 calls `obj.reindexObjectSecurity()` which iterates through a catalog query with the objects path as `path` parameter (see https://github.com/zopefoundation/Products.CMFCore/blob/master/src/Products/CMFCore/CMFCatalogAware.py#L110)

Now if you call `deleteLocalRoles` with `recursive=1` parameter (which the `deleteMembers` method does) it iterates through all subobjects of `ISiteRoot` and reindex their object security with the path query, which obviously leads to redundant object reindexing.

Possible fixes for this:

1. add a parameter to `CatalogAware.reindexObjectSecurity()` like `skip_subobjects` and set this to true while deleting localroles (`path=dict(query=path, depth=1)`)
2. call the `obj.reindexObjectSecurity()` only once at the end when using `recursive=1` in `deleteLocalroles` -> the subobjects get reindexed then too

Maybe someone has an even better idea for this. I'd be happy to create a PR for this.

**Comment by petschki** [comment]
oh ... sorry for the noise ... I've overseen the `reindex=0` parameter when calling recursively 🙈

**Comment by mauritsvanrees** [comment]
I do have some code in a client project that does it recursively, but stops searching part of the tree when you are 3 levels deep and still have not found a local role for this member. 
Depends on how deep your site is. I think in this one, with depth 4 it already visited 90 percent of the site, which would defeat the purpose of the patch. 
Might be useful to contribute with an env variable to enable it and set the depth.
