### ISSUE TITLE
Parameter `ignored` is not used

### ISSUE THREAD

**Issue by szakitibi** [zopefoundation/Products.CMFCore#141]
https://github.com/zopefoundation/Products.CMFCore/blob/48d0a67a6fee004f51e8048b652c3ca8c1174476/src/Products/CMFCore/namespace.py#L40-L52

**Comment by szakitibi** [comment]
Hmm... It is a 16 years old commit based on blame: https://github.com/zopefoundation/Products.CMFCore/blame/48d0a67a6fee004f51e8048b652c3ca8c1174476/src/Products/CMFCore/namespace.py#L40

Fixing it could be a braking change.

**Comment by szakitibi** [comment]
My use case is a custom `++add++` view test:

```python
    def test_add_view(self):
        add_view_traverser = api.content.get_view(name='add', context=container, request=request)
        add_view = add_view_traverser.traverse('MyType',  None) 
        ...
```
The `None` (or something) must be passed as second parameter, otherwise it drops `TypeError: AddViewTraverser.traverse() missing 1 required positional argument: 'ignored'`.

**Comment by davisagli** [comment]
We can't remove this parameter; it is part of the ITraversable interface: https://github.com/zopefoundation/zope.traversing/blob/master/src/zope/traversing/interfaces.py#L34

This particular ITraversable adapter names the parameter `ignored` to make it clearer that it's not used in this case.
