### ISSUE TITLE
reindexObjectSecurity missing update_metadata parameter (has the effect of full reindex)

### ISSUE THREAD

**Issue by valipod** [zopefoundation/Products.CMFCore#142]
## BUG/PROBLEM REPORT

When adding or removing a local role on a section to a user, a full reindex of all the objects in that section takes place, instead of reindexing only the `allowedRolesAndUsers`. This is because the `update_metadata=0` is not passed on https://github.com/zopefoundation/Products.CMFCore/blob/48d0a67a6fee004f51e8048b652c3ca8c1174476/src/Products/CMFCore/CMFCatalogAware.py#L128
[Further down the execution tree](https://github.com/zopefoundation/Products.CMFCore/blob/48d0a67a6fee004f51e8048b652c3ca8c1174476/src/Products/CMFCore/CMFCatalogAware.py#L82), `update_metadata` gets a default value of `1`, thus triggering a full reindex of all objects. In the case of `reindexObjectSecurity` we really don't want or need the metadata updated. This is also related to #140, since it vastly increases the amout of time it takes to reindex.

### What I did:

Added (or removed) some local role from a user, on a folder with a very large number of objects inside.

### What I expect to happen:

Receive an answer in a reasonable amount of time.

### What actually happened:

In my case, the answer took so much as 5 hours (of course depending on the number and type of objects - many images, PDFs, etc.).

### What version of Python and Zope/Addons I am using:

python 3.11, Zope 5.10, Plone 6.0.9 (6020)

**Comment by avoinea** [comment]
To me, it looks like a regression introduced in https://github.com/zopefoundation/Products.CMFCore/commit/a7b1e9cbf6fe5ab948fc0dccd81478e8e81281a2 Or maybe I miss something :thinking: @ale-rt?
