### ISSUE TITLE
Slim down package

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.CMFCore#17]
To ease Python 3 port it would be helpful to have a slimmed down CMFCore without the following dependencies:

* ZServer
* Products.ZSQLMethods
* Products.PythonScripts

Furthermore it this would be helpful for projects using CMFCore but without its TTW capabilities.

Could this be possible?

**Comment by dataflake** [comment]
First steps in PR #21

**Comment by dataflake** [comment]
Final status:

- ZServer is optional now
- ZSQL support is an extra in setup.py (see merged PR #21)
- PythonScripts cannot be made optional because Products.GenericSetup has them as dependency, which in itself is a hard dependency in CMFCore.

**Comment by tseaver** [comment]
FWIW, it would at least be feasible to make GenericSetup's dependency on PythonScripts optional:  it is mostly used for export / import of the skins tool (custom folder).
