### ISSUE TITLE
Document update from 2.2 --> 2.3

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.CMFCore#18]
What has to be done to be able to use version 2.3 instead of 2.2?
(I think even Plone still uses 2.2 and I did not succeed to update to 2.3 in union.cms.)

**Comment by dataflake** [comment]
Plone still uses the 2.2 series, correct. There is no specific guidance for the upgrade step from 2.2.x to 2.3 (pre-Zope 4) or 2.4 (Zope 4).

You're saying an upgrade failed for union.cms. If you provide more details about the specific failures someone may be able to help.

**Comment by icemac** [comment]
@dataflake Now I have specific question:

Since 2.3 [Products.CMFCore.CMFCatalogAware._getCatalogTool](https://github.com/zopefoundation/Products.CMFCore/blob/master/Products/CMFCore/CMFCatalogAware.py#L58) expects that the catalog is registered as a utility. (Version 2.2 used `getToolByName` there.) Outside the tests I did not find a place where the catalog is registered as a utility.
Did I miss some code or do I have to do this registration in my application code?

**Comment by dataflake** [comment]
@icemac The registration is done by the GenericSetup export/import configuration in CMFDefault since CMFDefault is supposed to contain actual applications built on top of the frameworks defined in CMFCore. So yes, if you don't use CMFDefault as your base you will have to perform the actual registrations in your application code.

**Comment by icemac** [comment]
@dataflake Do you mean these profiles: https://github.com/zopefoundation/Products.CMFDefault/tree/master/Products/CMFDefault/profiles? Which one does the needed registrations?

**Comment by dataflake** [comment]
A simple grep for ICatalogTool show you where:

```
$ grep -r ICatalogTool *
default/componentregistry.xml:  <utility interface="Products.CMFCore.interfaces.ICatalogTool"

```
