### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.CMFCore#23]
As the `master` branch now runs against a Python 3 capable Zope 4 this package can be ported to Python 3 as well.

Dependencies:

- [x] tox.ini #25
- [x] zopefoundation/Products.GenericSetup#47
- [x] port Products.CMFCore (this package), see #42 
- [x] no longer allow Python 3.6 builds to fail on Travis CI (revert part of f573382)

**Comment by dataflake** [comment]
All complete
