### ISSUE TITLE
Versions 2.2.6 to 2.2.12 not listed on PyPI

### ISSUE THREAD

**Issue by tobiasherp** [zopefoundation/Products.CMFCore#27]
The index page on PyPI (https://pypi.python.org/pypi/Products.CMFCore) lists the versions 2.2.5 (2011-11-01) and 2.3.0beta, but not the newer versions 2.2.6 to 2.2.12 from the 2.2 branch.

2.2.8 was a dependency for Plone 4.3.4, so I wondered. If there is no compelling reason to omit them, I suggest to add them to the list.

**Comment by dataflake** [comment]
By default, PyPI hides all old releases on the web page (they are all still available for setuptools or pip, though), but with the concurrent releases on several branches (2.2, 2.3 and 2.4) we decided to show the latest release from each of those branches to avoid confuion. But unsetting the default auto-hide option means that you have to manually update which versions to show each time you upload a new egg, which no one had done in a while.

I have updated the list of visible eggs to show the latest 2.2, 2.3 and 2.4 releases again. Clicking into the release will then show all older releases from the branch from the change log.

**Comment by icemac** [comment]
@tobiasherp The new PyPI provides a nice list of all released versions, see https://pypi.org/project/Products.CMFCore/#history
