### ISSUE TITLE
Replace im_func with __func__

### ISSUE THREAD

**Issue by ale-rt** [zopefoundation/Products.CMFCore#57]
Here: https://github.com/zopefoundation/Products.CMFCore/blob/bc815e2a43ba8ec221ca073631a3d672b2e557fc/Products/CMFCore/indexing.py#L72

**Comment by ale-rt** [comment]
I am unsure if doing a PR to fix this.
Apparently get_dispatcher is not used anywhere.
Can we just deprecate replace im_func with __func__ and deprecate that method?

**Comment by ale-rt** [comment]
Thanks! I just forgot this one

**Comment by dataflake** [comment]
@ale-rt I just couldn't stand seeing it on the list anymore 😉
