### ISSUE TITLE
Shut down launchpad.net for CMFCore

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Products.CMFCore#66]
URL:
https://launchpad.net/zope-cmfcore

Registered by @tseaver

**Comment by tseaver** [comment]
What exactly is it you want me to do there?  The bug tracker there is empty / disabled, and the homepage points to this repo.

**Comment by jugmac00** [comment]
Hi Tres, I'd suggest we delete the "empty" launchpad project for CMFCore, as neither additional infos are hosted there nor any historical ones.

Deleting a launchpad project works kinda weird, but is described here:
https://stackoverflow.com/a/17252314/672833

**Background information:**
I searched for information about what CMFCore is, and Google gave me the launchpad project site as one of the first hits. And actually I overlooked the smallish homepage link.
