### ISSUE TITLE
Finally getting rid of old-style actions

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Products.CMFCore#71]
Question for everyone: 11 years ago(!) I put in a `DeprecationWarning` that so-called "old-style" actions, meaning those stored in a simple tuple `_actions` on a action provider, will be going away in CMF 2.4. This may get rid of a nice chunk of code.

Is anything in Plone using those?

**Comment by icemac** [comment]
I don't know. I do not use CMF actions in my projects.

**Comment by dataflake** [comment]
I have made two attempts over several hours to remove "old-style" actions but I cannot figure out any clear delineation between the old and the "new-style" actions where I can make the cut. Some of the APIs are named identical, and looking at the code in the actions tool I can't figure out how it can get object-specific actions when the "old" actions are gone. It doesn't help that it's not possible to create a working CMFDefault site anymore to visually test this on a live site. I'm going to close this for now. This can be revisited if/when there is a working portal implementation that makes correct use of actions.
