### ISSUE TITLE
FSFile returns an undecoded String

### ISSUE THREAD

**Issue by drfho** [zopefoundation/Products.CMFCore#76]
hi @dataflake , 
I observed with **Py3/Zope4** that calling a text-based FSFile object by DTML, the return value  of FSFile is a stringfied/undecoded byte-string. So I simply added another function, which should do the work expected from Zope2. The effect can be seen on the screen image:

![CMFCore_return_str](https://user-images.githubusercontent.com/29705216/58032929-d50d4800-7b23-11e9-882f-b8e0aad76f8e.png)

**QUICKFIX**
https://github.com/zopefoundation/Products.CMFCore/blob/master/Products/CMFCore/FSFile.py#L114
```
+
+    def decode_data(self,codec='utf8'):
+        self._updateFromFS()
+        return self._readFile(0).decode(codec)
```

I suppose this is not really elegant, but I do not have a better idea how to solve that issue using e.g. the __str__  pipline. 
Please give me a feedback, whether I should add this to Pull Request?
Thanks
f

**Comment by d-maurer** [comment]
drfho wrote at 2019-5-20 08:45 -0700:
>hi @dataflake ,
>I observed with **Py3/Zope4** that calling a text-based FSFile object by DTML, the return value  of FSFile is a stringfied/undecoded byte-string. So I simply added another function, which should do the work expected from Zope2. The effect can be seen on the screen image:
>
>![CMFCore_return_str](https://user-images.githubusercontent.com/29705216/58032929-d50d4800-7b23-11e9-882f-b8e0aad76f8e.png)
>
>**QUICKFIX**
>https://github.com/zopefoundation/Products.CMFCore/blob/master/Products/CMFCore/FSFile.py#L114
>```
>+
>+    def decode_data(self,codec='utf8'):
>+        self._updateFromFS()
>+        return self._readFile(0).decode(codec)
>```

A `FSFile` has a good chance to contain binary data -- data
not decodable via `utf8`. Use "latin1" instead -- the
standard encoding mapping byte strings to `str` in Python 3.

Of course, this may result in problems later should the result
arrive in a response (if `zpublisher-default-encoding` cannot
encode it).
To avoid such problems, you might consider using 'ascii' with
an escape mechanism (if the result is primarily destined for
presentation).

**Comment by drfho** [comment]
Hi @d-maurer 
many thanks for the quick reply: you are right, to avoid complications with binary files, maybe we should leave any decoding in the object's code. Without str()-tranformation FSFile-object will return a text/css  stream in an appropiate format, Like this:
`<dtml-var "style_css.data()">`
works if that data()-function 
```
+    def data(self):
+        self._updateFromFS()
+        return self._readFile(0)
```
will be added here
https://github.com/zopefoundation/Products.CMFCore/blob/master/Products/CMFCore/FSFile.py#L114

Hint: removing just the str()-transformation in __str__ will result in a **type error** : ___str__ returned non-string (type bytes)_
```
    def __str__(self):
       self._updateFromFS()
-      return str(self._readFile(0))
+      return self._readFile(0)
```
Best regards
f

**Comment by icemac** [comment]
Can this issue be resolved in Zope or should it be moved to `CMFCore`?

**Comment by dwt** [comment]
[In Zope zope.OFS.Image.File this is solved this way](https://github.com/zopefoundation/Zope/blob/20d29682acacb73d7fb41d5e37beb46fa87a19b1/src/OFS/Image.py#L673). It may be wise to do things the same way here to avoid surprises. What they provide is a `__bytes__` method, which to my understanding would allow you to write something like `bytes(someCMFCoreFile).decode(theEncodingYouKnow`. Also the `__str__()` method tries to auto-decode the file with the default encoding. (Which should nowadays usually be utf8).

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2019-5-20 23:18 -0700:
>Can this issue be resolved in Zope or should it be moved to `CMFCore`?

`FSFile` should behave comparable to Zope's `File`.
If I had to implement `FSFile`, I would try to derive from `File`
(I have not checked whether `FSFile` actually does this).
At least, there are common aspects which should be handled by
the same code.

When I remember right, then `File` differentiates its behaviour
depending on the "content_type". For a `text/*` content type, it
displays the file content in the ZMI; for  `application/*` it does
not (because this is likely nonsense).
`FSFile` could employ similar logic (ideally inherited logic;
maybe from a common ancestor).

**Comment by dataflake** [comment]
The `__str__` method in `OFS.Image.File` distinguishes between Python 2 and Python 3. Under Python 2 it sends its data through `str`, just like `FSFile` does now. For Python 3, it decodes its data using the  default encoding set by `zpublisher-default-encoding`. I am guessing emulating the same behavior would help here.

The `__bytes__` method  in `OFS.Image.File` just calls `bytes` on the data and returns the result.

**Comment by dataflake** [comment]
I have added a PR that emulates the behavior of `OFS.Image.File`.

It should be noted that you should not call `str` on a file that contains undecodable binary data. The `bytes` built-in should be used on those and a corresponding `__bytes__` method is part of the PR.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2019-5-24 17:34 -0700:
>The `__str__` method in `OFS.Image.File` distinguishes between Python 2 and Python 3. Under Python 2 it sends its data through `str`, just like `FSFile` does now. For Python 3, it decodes its data using the  default encoding set by `zpublisher-default-encoding`.

I do not think that this is the correct encoding -- at least not
for general files.

Many file types contain binary data; the only decoding adequate
for binary data is "latin1" - which maps byte "b" to
unicode codepoint "b".
Nowadays, one would recommend "utf8" as default encoding.
If we try to "utf8"-decode binary data, there is a high chance
to get a "DecodingError" (unless the binary data actually is ASCII data).


I recommend to make `__str__` dependent on the file's `content_type`.
Let `__str__` behave as `repr` for non `text` files.
If `content_type` is `text/*` and contains a `charset` parameter,
then use this charset for decoding; otherwise, look for a
BOM ("Byte Order Mark") which would define the charset;
otherwise try `utf8` (which nowadays is often used and fails
quite reliably if applied to a non utf8-encoded byte stream);
finally fall back to some default charset (maybe `zpublisher-default-encoding`)
with a replacement for characters not decodable.

**Comment by drfho** [comment]
Hi @dataflake,
pull#77 works perfect, thank you very much!

May I make another suggestion for FSFile.py: 
the list of registered file extensions (and thus files published  via Zope) might be extended to filetypes which are common for web design today:

FSFile.py LINE 193
```
   registerFileExtension('css', FSFile)
+  registerFileExtension('map', FSFile)
+  registerFileExtension('svg', FSFile)
+  registerFileExtension('ttf', FSFile)
+  registerFileExtension('eot', FSFile)
+  registerFileExtension('woff', FSFile)
+  registerFileExtension('woff2', FSFile)
```
Ref: https://github.com/zopefoundation/Products.CMFCore/blob/a983ee3082bdf915daa520d8f0bf0b0e1caac5ce/Products/CMFCore/FSFile.py#L193

**Comment by dwt** [comment]
@d-maurer Although I tend to agree with latin1 vs utf8, I think it is critical that FSFile here works the same as File in Zope, so whatever you guys choose, please choose the same solution.

That being said, I think for the encoding problem alone, having the __str__ of a file being it's content is a bad idea and should be an API that is deprecated.

**Comment by dataflake** [comment]
> May I make another suggestion for FSFile.py:
> the list of registered file extensions (and thus files published via Zope) might be extended to filetypes which are common for web design today:
> 
> FSFile.py LINE 193
> 
> ```
>    registerFileExtension('css', FSFile)
> +  registerFileExtension('map', FSFile)
> +  registerFileExtension('svg', FSFile)
> +  registerFileExtension('ttf', FSFile)
> +  registerFileExtension('eot', FSFile)
> +  registerFileExtension('woff', FSFile)
> +  registerFileExtension('woff2', FSFile)
> ```

This does not belong into this issue. I have added that to master instead.

**Comment by dataflake** [comment]
I have added some more intelligence to the encoding selection while also retaining the current OFS.Image behavior of letting it blow up on non-text binary data. There's also a DeprecationWarning for that non-text data case.
