### ISSUE TITLE
Add Travis-CI integration

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.CMFCore#8]
Travis CI knows about this project: https://travis-ci.org/zopefoundation/Products.CMFCore/branches
But it does not make any builds for it.

**Comment by tseaver** [comment]
@icemac I have activated the project, but there is no `.travis.yml` file:  can you add one?

**Comment by icemac** [comment]
Fixed by #9.

**Comment by mauritsvanrees** [comment]
@icemac Could you do this for the 2.2 branch as well?

**Comment by icemac** [comment]
@mauritsvanrees See #11

**Comment by mauritsvanrees** [comment]
Thanks, merged.
