### ISSUE TITLE
Using CookieCrumbler (without the CMF)

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Products.CMFCore#92]
I used to use the standalone CookieCrumbler until now, but it does not seem to work with Python 3 anymore, so I installed CMFCore, added a CookieCrumbler to my site and used the standalone's login objects.

This works fine on my local machine (using http://localhost:port). But on my server, I always get a failed login (unless I logged in via HTML first).

I tried to eliminate some possible sources of error:

- It's not https, I get the same error on http
- It's not the WSGI-server (waitress) as I use it also on my local machine
- It's not the server's webserver (I use nginx), I have the same problem if I access my site directly from http://my.server.address:port (waitress)

Maybe I'm doing it all wrong, what's the correct way to set up a CookieCrumbler?

**Comment by d-maurer** [comment]
Georg Pfolz wrote at 2020-5-12 05:36 -0700:
>I used to use the standalone CookieCrumbler until now, but it does not seem to work with Python 3 anymore, so I installed CMFCore, added a CookieCrumbler to my site and used the standalone's login objects.

I recommend to use `Products.PluggableAuthService`.
It implements a flexible mini framework for (almost) all
aspects of authentication and authorization.
It is configured by plugin activations.

One of its plugins support cookie authentication (comparable to
`CookieCrumbler`).

**Comment by georgpfolz** [comment]
Ok, thank you, I will try it.

**Comment by jugmac00** [comment]
I concur with @d-maurer - I also switched from CookieCrumbler to PAS when I moved from Zope 2 to Zope 4. Works like a charm.

**Comment by georgpfolz** [comment]
Thank you @d-maurer, @jugmac00, PAS was what I needed! Works fine for me!

**Comment by icemac** [comment]
Closing this issue as the question seems to be solved.
